name: opis_lint

on:
  pull_request:

permissions:
  contents: read

jobs:
  lint_job:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code lint
        uses: actions/checkout@v4
      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: "24.13.0"
      - name: install dependencies
        run: npm ci
      - name: lint code
        run: npm run lint:fix